services:
  web:
    image: web_status:v1.0
    build:
      context: .
    ports:
      - "5004:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_ENV_LOCAL=production
    restart: always
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
